version: '3.4'
services:
  sormas:
    restart: unless-stopped
    links:
      - postgres
    image: hzibraunschweig/sormas-application:${SORMAS_DOCKER_VERSION}
    ports:
      - '6080:6080'
      - '6081:6081'
      - '6048:6048'
    env_file:
      - ./.env
    volumes:
      - ${SORMAS_PATH}/documents:/opt/sormas/documents
      - ${SORMAS_PATH}/custom:/opt/sormas/custom
      - ${SORMAS_PATH}/sormas2sormas:/opt/sormas/sormas2sormas
      - ${SORMAS_PATH}/sormas-logs:/opt/domains/sormas/logs
    mem_limit: ${APPSERVER_MEM}
    mem_reservation: ${APPSERVER_MEM_RESERVED}
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:6080/sormas-ui/login" ]
      interval: 30s
      timeout: 7s
      retries: 3
      start_period: 300s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: unless-stopped
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/sormas-postgres:${SORMAS_DOCKER_VERSION}
    env_file:
      - ./.env
    volumes:
      - ${SORMAS_PATH}/psqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: ${DB_MEM}
    mem_reservation: ${DB_MEM_RESERVED}
    healthcheck:
      test: [ "CMD", "psql", "-U", "${SORMAS_POSTGRES_USER}", "-c", "SELECT 1;", "${DB_NAME}" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  data-gen:
    build:
      context: src/
      args:
        - DOCKERIZED=false
        - SORMAS_VERSION=${SORMAS_VERSION}
        - OPENAPI_GENERATOR_VERSION=${OPENAPI_GENERATOR_VERSION}
        - PERFORMANCE_LOG_DIR=${PERFORMANCE_LOG_DIR}
    env_file:
      - ./.env
    depends_on:
      sormas:
        condition: service_healthy
